name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build application for macOS
        run: npx pkg pvmount.js --output pvmount --target node18-macos-x64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./pvmount
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
